# Generated by Django 4.2.13 on 2024-06-11 10:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("request", "0006_notificationresponseid_alter_application_reference_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicalreview",
            name="reason",
            field=models.TextField(blank=True, max_length=5000, null=True),
        ),
        migrations.AddField(
            model_name="review",
            name="reason",
            field=models.TextField(blank=True, max_length=5000, null=True),
        ),
    ]
