# Generated by Django 4.2.13 on 2024-06-12 15:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("request", "0007_historicalreview_reason_review_reason"),
    ]

    operations = [
        migrations.AddField(
            model_name="registrar",
            name="active",
            field=models.BooleanField(default=True),
        ),
    ]
