# Generated by Django 4.2.13 on 2024-06-14 13:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("request", "0007_historicalreview_reason_review_reason"),
    ]

    operations = [
        migrations.AlterField(
            model_name="registrant",
            name="type",
            field=models.CharField(
                choices=[
                    ("central_government", "Central government department or agency"),
                    (
                        "alb",
                        "Non-departmental body - also known as an arm's length body",
                    ),
                    ("parish_council", "Parish, town or community council"),
                    ("local_authority", "District, borough, city or county council"),
                    ("fire_service", "Fire service"),
                    ("combined_authority", "Combined or unitary authority"),
                    ("pcc", "Police and crime commissioner"),
                    ("joint_authority", "Joint authority"),
                    ("joint_committee", "Joint committee"),
                    (
                        "psb_group",
                        "Organisation representing a group of public sector bodies",
                    ),
                    (
                        "psb_profession",
                        "Organisation representing a profession across public sector bodies",
                    ),
                ],
                max_length=100,
            ),
        ),
    ]
