# Generated by Django 4.2.13 on 2024-08-05 10:25

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("request", "0011_alter_application_status_and_more"),
        ("request", "0012_alter_application_status"),
    ]

    operations = []
