# Generated by Django 4.2.13 on 2024-09-09 14:08

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("request", "0019_historicalregistrypublishedperson_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="historicalregistrantperson",
            name="history_user",
        ),
        migrations.RemoveField(
            model_name="historicalregistrarperson",
            name="history_user",
        ),
        migrations.RemoveField(
            model_name="historicalregistrarperson",
            name="registrar",
        ),
        migrations.RemoveField(
            model_name="historicalregistrypublishedperson",
            name="history_user",
        ),
        migrations.DeleteModel(
            name="HistoricalRegistrant",
        ),
        migrations.DeleteModel(
            name="HistoricalRegistrantPerson",
        ),
        migrations.DeleteModel(
            name="HistoricalRegistrarPerson",
        ),
        migrations.DeleteModel(
            name="HistoricalRegistryPublishedPerson",
        ),
    ]
