# Generated by Django 4.2.13 on 2025-04-24 12:35

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("request", "0008_registrar_active"),
        ("request", "0021_historicalregistrypublishedperson_and_more"),
    ]

    operations = []
