# Generated by Django 4.2.13 on 2025-04-24 12:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("request", "0022_merge_20250424_1235"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicalregistrar",
            name="active",
            field=models.BooleanField(default=True),
        ),
    ]
